apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  admin-password:   {{ .Values.secret.adminPassword }}
  faculty-password: {{ .Values.secret.facultyPassword }}